-- Create User Activity Log table
CREATE TABLE IF NOT EXISTS public.user_activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  activity_type text NOT NULL CHECK (activity_type IN ('login', 'logout')),
  timestamp timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.user_activity ENABLE ROW LEVEL SECURITY;

-- Policies for user_activity
DROP POLICY IF EXISTS "Allow public inserts of user activities" ON public.user_activity;
CREATE POLICY "Allow public inserts of user activities"
  ON public.user_activity FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admins to read all activities" ON public.user_activity;
CREATE POLICY "Allow admins to read all activities"
  ON public.user_activity FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users
      WHERE LOWER(email) IN ('12k21rakeshkannam@gmail.com', 'admin@careerbridge.com', 'kumardhanush6494@gmail.com', 'cheappcgamesrake@gmail.com')
    )
  );
