-- CareerBridge AI Database Schema Migration
-- Designed to replace local storage with secure Supabase storage.

-- 1. Create User Profiles table (linked to auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  xp integer default 0 not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

alter table public.profiles enable row level security;

create policy "Allow public read of profiles"
  on public.profiles for select
  using (true);

create policy "Allow users to update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Trigger to automatically create a profile when a user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url, xp)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url',
    0
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Create Solved Aptitude table
create table if not exists public.solved_aptitude (
  user_id uuid references auth.users(id) on delete cascade not null,
  question_key text not null, -- Stores category_id format (e.g. 'quantitative_1')
  solved_at timestamptz default now() not null,
  primary key (user_id, question_key)
);

alter table public.solved_aptitude enable row level security;

create policy "Users can read own solved aptitude records"
  on public.solved_aptitude for select
  using (auth.uid() = user_id);

create policy "Users can insert own solved aptitude records"
  on public.solved_aptitude for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own solved aptitude records"
  on public.solved_aptitude for delete
  using (auth.uid() = user_id);


-- 3. Create Solved Coding table
create table if not exists public.solved_coding (
  user_id uuid references auth.users(id) on delete cascade not null,
  question_id text not null, -- Coding question ID/slug
  solved_at timestamptz default now() not null,
  primary key (user_id, question_id)
);

alter table public.solved_coding enable row level security;

create policy "Users can read own solved coding records"
  on public.solved_coding for select
  using (auth.uid() = user_id);

create policy "Users can insert own solved coding records"
  on public.solved_coding for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own solved coding records"
  on public.solved_coding for delete
  using (auth.uid() = user_id);


-- 4. Create Coding Submissions table (History)
create table if not exists public.coding_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  question_id text not null,
  question_title text not null,
  code text not null,
  language text not null,
  status text not null, -- 'Accepted', 'Wrong Answer', 'Time Limit Exceeded', etc.
  passed_test_cases integer default 0 not null,
  total_test_cases integer default 0 not null,
  submitted_at timestamptz default now() not null
);

alter table public.coding_submissions enable row level security;

create policy "Users can read own submissions"
  on public.coding_submissions for select
  using (auth.uid() = user_id);

create policy "Users can insert own submissions"
  on public.coding_submissions for insert
  with check (auth.uid() = user_id);


-- 5. Create Company Interactions table (saved / applied / steps)
create table if not exists public.company_interactions (
  user_id uuid references auth.users(id) on delete cascade not null,
  company_slug text not null,
  is_saved boolean default false not null,
  is_applied boolean default false not null,
  prep_steps jsonb default '[]'::jsonb not null, -- Stores tracking checkmarks
  interacted_at timestamptz default now() not null,
  primary key (user_id, company_slug)
);

alter table public.company_interactions enable row level security;

create policy "Users can read own company interactions"
  on public.company_interactions for select
  using (auth.uid() = user_id);

create policy "Users can manage own company interactions"
  on public.company_interactions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- 6. Create Resume Analyses table
create table if not exists public.resume_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  score integer not null,
  analysis_data jsonb not null, -- Stores detailed AI feedback
  analyzed_at timestamptz default now() not null
);

alter table public.resume_analyses enable row level security;

create policy "Users can read own resume analyses"
  on public.resume_analyses for select
  using (auth.uid() = user_id);

create policy "Users can insert own resume analyses"
  on public.resume_analyses for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own resume analyses"
  on public.resume_analyses for delete
  using (auth.uid() = user_id);


-- 7. Create System Notifications table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade, -- NULL means global notifications
  title text not null,
  message text not null,
  type text not null, -- 'system', 'achievement', 'reminder', etc.
  link text,
  created_at timestamptz default now() not null
);

alter table public.notifications enable row level security;

create policy "Users can view relevant notifications"
  on public.notifications for select
  using (user_id is null or user_id = auth.uid());

create policy "Allow all users to insert notifications"
  on public.notifications for insert
  with check (true);

create policy "Allow all users to delete notifications"
  on public.notifications for delete
  using (true);


-- 8. Create Read Notifications junction table (for read states)
create table if not exists public.read_notifications (
  user_id uuid references auth.users(id) on delete cascade not null,
  notification_id bigint references public.notifications(id) on delete cascade not null,
  read_at timestamptz default now() not null,
  primary key (user_id, notification_id)
);

alter table public.read_notifications enable row level security;

create policy "Users can read own read states"
  on public.read_notifications for select
  using (auth.uid() = user_id);

create policy "Users can mark notifications as read"
  on public.read_notifications for insert
  with check (auth.uid() = user_id);
